TRAIN:
  ENABLE: True
  DATASET: cataract #kinetics
  BATCH_SIZE: 64
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_EPOCH_RESET: True
  CHECKPOINT_FILE_PATH: /home/pangy/disk/video_detection/SlowFast/checkpoints/SLOWFAST_8x8_R50.pyth
DATA:
  PATH_TO_DATA_DIR: "/home/pangy/disk/cataracts_dataset/videos"
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3, 3]
  PATH_PREFIX: ""
  IN_FPS: 60
  OUT_FPS: 1
  READ_VID_FILE: True
  VID_FILE_EXT: ".mp4"
  IMG_FILE_EXT: ".jpg"
  IMG_FILE_FORMAT: "frame_{:010d}.jpg"
  SAMPLE_SIZE: [256, 256]
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.1
  BASE_LR_SCALE_NUM_SHARDS: True #add
  LR_POLICY: cosine
  MAX_EPOCH: 200 #196
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 34.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
  LAYER_DECAY: 1.0 #add
MODEL:
  NUM_CLASSES: 18 #400
  ARCH: slowfast
  MODEL_NAME: SlowFast #revised
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: cataract #kinetics
  BATCH_SIZE: 64
  NUM_SPATIAL_CROPS: 3 #add
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
# MVIT:
#   DEPTH: 16 #add
NUM_GPUS: 1 #8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
